{% set name = "n2v" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/n2v-{{ version }}.tar.gz
  sha256: 9077f2f4181f7ca52b8282b142408b095e2f2aaa946909558b1d11cef2434537

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bioimage.core
    - csbdeep >=0.7.2,<0.8.0
    - imagecodecs >=2020.2.18
    - matplotlib-core          # Imported but not listed as requirement
    - numpy
    - pillow
    - python >=3.7
    - ruamel.yaml >=0.16.10
    - six                      # Imported but not listed as requirement
    - tensorflow               # Imported but not listed as requirement
    - tifffile
    - tqdm                     # Imported but not listed as requirement

test:
  imports:
    - n2v
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juglab/n2v/
  summary: Noise2Void allows the training of a denoising CNN from individual noisy images. This implementationextends CSBDeep.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
